In [163]:
## import necessary libraries

import pandas as pd
import nltk
import string
import gensim
from scipy import spatial
from sklearn.feature_extraction.text import TfidfVectorizer
from sent2vec.vectorizer import Vectorizer
from sent2vec.splitter import Splitter
from gensim.models import Word2Vec
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.metrics.pairwise import cosine_similarity
from gensim.scripts.glove2word2vec import glove2word2vec

In [19]:
df = pd.read_csv('./potential-talents - Aspiring human resources - seeking human resources.csv')
df.head()

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,NaN
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+,NaN
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,NaN
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,NaN
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,NaN

## Word2Vec

In [129]:
job_desc_list = []

for num in range(len(df)):
    desc = df.iloc[num]['job_title']
    ## remove punctuation from job description    
    for symbol in list(string.punctuation):
        desc = desc.replace(symbol, ' ')
    
    ## write out acronyms for human resource positions
    desc = nltk.word_tokenize(desc)
    for word in range(len(desc)):
        if desc[word] == 'HR':
            desc[word] = 'Human Resources'
        elif desc[word] == 'CHRO':
            desc[word] = 'Chief Human Resources Officer'
        elif desc[word] == 'GPHR':
            desc[word] = 'General Professional Human Resources'
        elif desc[word] == 'SPHR':
            desc[word] = 'Senior Professional Human Resources'
        elif desc[word] in ['EPIK', 'Celal', 'Bayar', 'Humber', 'ENGIE', 'Buckhead', 'Luxottica', 'Beneteau', 'ScottMadden', 
                            'Nortia', 'Schwan', 'Endemol', 'JTI', 'Styczynski', 'Westfield', 'Kokomo', 'Delphi', 'Loparex']:
            desc[word] = ''
        desc[word] = desc[word].lower()

    ## remove stopwords
    desc = [token for token in desc if token not in stopwords.words('english')]
    desc = [token for token in desc if not token.isdigit()]
    
    desc = ' '.join(desc)
    desc = nltk.word_tokenize(desc)
    
    job_desc_list.append(desc)

In [130]:
job_desc_list.append(['seeking', 'human', 'resources'])

In [131]:
job_desc_list

[['c',
  'bauer',
  'college',
  'business',
  'graduate',
  'magna',
  'cum',
  'laude',
  'aspiring',
  'human',
  'resources',
  'professional'],
 ['native', 'english', 'teacher', 'english', 'program', 'korea'],
 ['aspiring', 'human', 'resources', 'professional'],
 ['people', 'development', 'coordinator', 'ryan'],
 ['advisory', 'board', 'member', 'university'],
 ['aspiring', 'human', 'resources', 'specialist'],
 ['student', 'college', 'aspiring', 'human', 'resources', 'generalist'],
 ['human', 'resources', 'senior', 'specialist'],
 ['student', 'college', 'aspiring', 'human', 'resources', 'generalist'],
 ['seeking', 'human', 'resources', 'hris', 'generalist', 'positions'],
 ['student', 'chapman', 'university'],
 ['svp',
  'chief',
  'human',
  'resources',
  'officer',
  'marketing',
  'communications',
  'csr',
  'officer',
  'houston',
  'woodlands',
  'energy',
  'general',
  'professional',
  'human',
  'resources',
  'senior',
  'professional',
  'human',
  'resources'],
 ['human', 'resources', 'coordinator', 'intercontinental', 'atlanta'],
 ['c',
  'bauer',
  'college',
  'business',
  'graduate',
  'magna',
  'cum',
  'laude',
  'aspiring',
  'human',
  'resources',
  'professional'],
 ['c',
  'bauer',
  'college',
  'business',
  'graduate',
  'magna',
  'cum',
  'laude',
  'aspiring',
  'human',
  'resources',
  'professional'],
 ['native', 'english', 'teacher', 'english', 'program', 'korea'],
 ['aspiring', 'human', 'resources', 'professional'],
 ['people', 'development', 'coordinator', 'ryan'],
 ['c',
  'bauer',
  'college',
  'business',
  'graduate',
  'magna',
  'cum',
  'laude',
  'aspiring',
  'human',
  'resources',
  'professional'],
 ['native', 'english', 'teacher', 'english', 'program', 'korea'],
 ['aspiring', 'human', 'resources', 'professional'],
 ['people', 'development', 'coordinator', 'ryan'],
 ['advisory', 'board', 'member', 'university'],
 ['aspiring', 'human', 'resources', 'specialist'],
 ['student', 'college', 'aspiring', 'human', 'resources', 'generalist'],
 ['human', 'resources', 'senior', 'specialist'],
 ['aspiring',
  'human',
  'resources',
  'management',
  'student',
  'seeking',
  'internship'],
 ['seeking', 'human', 'resources', 'opportunities'],
 ['aspiring',
  'human',
  'resources',
  'management',
  'student',
  'seeking',
  'internship'],
 ['seeking', 'human', 'resources', 'opportunities'],
 ['c',
  'bauer',
  'college',
  'business',
  'graduate',
  'magna',
  'cum',
  'laude',
  'aspiring',
  'human',
  'resources',
  'professional'],
 ['native', 'english', 'teacher', 'english', 'program', 'korea'],
 ['aspiring', 'human', 'resources', 'professional'],
 ['people', 'development', 'coordinator', 'ryan'],
 ['advisory', 'board', 'member', 'university'],
 ['aspiring', 'human', 'resources', 'specialist'],
 ['student', 'college', 'aspiring', 'human', 'resources', 'generalist'],
 ['human', 'resources', 'senior', 'specialist'],
 ['student', 'college', 'aspiring', 'human', 'resources', 'generalist'],
 ['seeking', 'human', 'resources', 'hris', 'generalist', 'positions'],
 ['student', 'chapman', 'university'],
 ['svp',
  'chief',
  'human',
  'resources',
  'officer',
  'marketing',
  'communications',
  'csr',
  'officer',
  'houston',
  'woodlands',
  'energy',
  'general',
  'professional',
  'human',
  'resources',
  'senior',
  'professional',
  'human',
  'resources'],
 ['human', 'resources', 'coordinator', 'intercontinental', 'atlanta'],
 ['c',
  'bauer',
  'college',
  'business',
  'graduate',
  'magna',
  'cum',
  'laude',
  'aspiring',
  'human',
  'resources',
  'professional'],
 ['native', 'english', 'teacher', 'english', 'program', 'korea'],
 ['aspiring', 'human', 'resources', 'professional'],
 ['people', 'development', 'coordinator', 'ryan'],
 ['advisory', 'board', 'member', 'university'],
 ['aspiring', 'human', 'resources', 'specialist'],
 ['student', 'college', 'aspiring', 'human', 'resources', 'generalist'],
 ['human', 'resources', 'senior', 'specialist'],
 ['student', 'college', 'aspiring', 'human', 'resources', 'generalist'],
 ['seeking', 'human', 'resources', 'hris', 'generalist', 'positions'],
 ['student', 'chapman', 'university'],
 ['svp',
  'chief',
  'human',
  'resources',
  'officer',
  'marketing',
  'communications',
  'csr',
  'officer',
  'houston',
  'woodlands',
  'energy',
  'general',
  'professional',
  'human',
  'resources',
  'senior',
  'professional',
  'human',
  'resources'],
 ['human', 'resources', 'coordinator', 'intercontinental', 'atlanta'],
 ['c',
  'bauer',
  'college',
  'business',
  'graduate',
  'magna',
  'cum',
  'laude',
  'aspiring',
  'human',
  'resources',
  'professional'],
 ['aspiring', 'human', 'resources', 'professional'],
 ['people', 'development', 'coordinator', 'ryan'],
 ['aspiring', 'human', 'resources', 'specialist'],
 ['human', 'resources', 'senior', 'specialist'],
 ['seeking', 'human', 'resources', 'hris', 'generalist', 'positions'],
 ['student', 'chapman', 'university'],
 ['svp',
  'chief',
  'human',
  'resources',
  'officer',
  'marketing',
  'communications',
  'csr',
  'officer',
  'houston',
  'woodlands',
  'energy',
  'general',
  'professional',
  'human',
  'resources',
  'senior',
  'professional',
  'human',
  'resources'],
 ['human', 'resources', 'coordinator', 'intercontinental', 'atlanta'],
 ['experienced',
  'retail',
  'manager',
  'aspiring',
  'human',
  'resources',
  'professional'],
 ['human', 'resources', 'staffing', 'recruiting', 'professional'],
 ['human', 'resources', 'specialist'],
 ['director', 'human', 'resources', 'north', 'america', 'groupe'],
 ['retired',
  'army',
  'national',
  'guard',
  'recruiter',
  'office',
  'manager',
  'seeking',
  'position',
  'human',
  'resources'],
 ['human', 'resources', 'generalist', 'inc'],
 ['business',
  'management',
  'major',
  'aspiring',
  'human',
  'resources',
  'manager'],
 ['aspiring',
  'human',
  'resources',
  'manager',
  'seeking',
  'internship',
  'human',
  'resources'],
 ['human', 'resources', 'professional'],
 ['staffing',
  'seeking',
  'human',
  'resources',
  'payroll',
  'administrative',
  'professionals'],
 ['aspiring',
  'human',
  'resources',
  'professional',
  'passionate',
  'helping',
  'create',
  'inclusive',
  'engaging',
  'work',
  'environment'],
 ['human',
  'resources',
  'conflict',
  'management',
  'policies',
  'procedures',
  'talent',
  'management',
  'benefits',
  'compensation'],
 ['human', 'resources', 'generalist'],
 ['liberal', 'arts', 'major', 'aspiring', 'human', 'resources', 'analyst'],
 ['junior', 'mes', 'engineer', 'information', 'systems'],
 ['senior',
  'human',
  'resources',
  'business',
  'partner',
  'heil',
  'environmental'],
 ['aspiring',
  'human',
  'resources',
  'professional',
  'energetic',
  'team',
  'focused',
  'leader'],
 ['human', 'resources', 'manager', 'shine', 'north', 'america'],
 ['human', 'resources', 'professional', 'world', 'leader', 'gis', 'software'],
 ['rrp',
  'brand',
  'portfolio',
  'executive',
  'japan',
  'tobacco',
  'international'],
 ['information',
  'systems',
  'specialist',
  'programmer',
  'love',
  'data',
  'organization'],
 ['bachelor', 'science', 'biology', 'victoria', 'university', 'wellington'],
 ['human', 'resources', 'management', 'major'],
 ['director', 'human', 'resources', 'ey'],
 ['undergraduate', 'research', 'assistant', 'lab'],
 ['lead', 'official', 'western', 'illinois', 'university'],
 ['seeking',
  'employment',
  'opportunities',
  'within',
  'customer',
  'service',
  'patient',
  'care'],
 ['admissions',
  'representative',
  'community',
  'medical',
  'center',
  'long',
  'beach'],
 ['seeking',
  'human',
  'resources',
  'opportunities',
  'open',
  'travel',
  'relocation'],
 ['student', 'state', 'university'],
 ['student',
  'indiana',
  'university',
  'business',
  'management',
  'retail',
  'manager',
  'hardware',
  'paint'],
 ['aspiring', 'human', 'resources', 'professional'],
 ['student'],
 ['seeking', 'human', 'resources', 'position'],
 ['aspiring',
  'human',
  'resources',
  'manager',
  'graduating',
  'may',
  'seeking',
  'entry',
  'level',
  'human',
  'resources',
  'position',
  'st',
  'louis'],
 ['human', 'resources', 'generalist'],
 ['business', 'intelligence', 'analytics', 'travelers'],
 ['always', 'set', 'success'],
 ['director', 'administration', 'excellence', 'logging'],
 ['seeking', 'human', 'resources']]

In [132]:
vectorizer = Vectorizer()
vectorizer.word2vec(job_desc_list, pretrained_vectors_path= './GoogleNews-vectors-negative300.bin')
vectors = vectorizer.vectors

In [133]:
dist_1 = spatial.distance.cosine(vectors[-1], vectors[0])
dist_2 = spatial.distance.cosine(vectors[-1], vectors[2])
print('dist_1: {0}, dist-2: {1}'.format(dist_1, dist_2))

dist_1: 0.611827164888382, dist-2: 0.29940420389175415

In [89]:
test_df = df
test_df.head()

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,NaN
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+,NaN
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,NaN
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,NaN
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,NaN

In [134]:
scores = []
for num in range(len(job_desc_list) - 1):
    scores.append(1 - spatial.distance.cosine(vectors[num], vectors[-1]))
    
test_df['word2vec_fit'] = scores
test_df

,id,job_title,location,connection,fit,word2vec_fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.929219,0.388173
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+,0.948172,0.104410
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.984994,0.700596
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,0.973138,0.291818
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,0.935457,0.229988
...,...,...,...,...,...,...
99,100,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103,0.914459,0.729863
100,101,Human Resources Generalist at Loparex,"Raleigh-Durham, North Carolina Area",500+,0.982065,0.750962
101,102,Business Intelligence and Analytics at Travelers,Greater New York City Area,49,0.976543,0.282647
102,103,Always set them up for Success,Greater Los Angeles Area,500+,0.983066,0.133268
103,104,Director Of Administration at Excellence Logging,"Katy, Texas",500+,0.968243,0.281777

## BERT

In [84]:
bert_list = []

for num in range(len(df)):
    desc = df.iloc[num]['job_title']
    ## remove punctuation from job description    
    for symbol in list(string.punctuation):
        desc = desc.replace(symbol, ' ')
        
    ## write out acronyms for human resource positions
    desc = nltk.word_tokenize(desc)
    for word in range(len(desc)):
        if desc[word] == 'HR':
            desc[word] = 'Human Resources'
        elif desc[word] == 'CHRO':
            desc[word] = 'Chief Human Resources Officer'
        elif desc[word] == 'GPHR':
            desc[word] = 'General Professional in Human Resources'
        elif desc[word] == 'SPHR':
            desc[word] = 'Senior Professional in Human Resources'
            
    desc = ' '.join(desc)
    bert_list.append(desc)

In [85]:
bert_list.append('seeking human resources')

In [86]:
bert_list

['2019 C T Bauer College of Business Graduate Magna Cum Laude and aspiring Human Resources professional',
 'Native English Teacher at EPIK English Program in Korea',
 'Aspiring Human Resources Professional',
 'People Development Coordinator at Ryan',
 'Advisory Board Member at Celal Bayar University',
 'Aspiring Human Resources Specialist',
 'Student at Humber College and Aspiring Human Resources Generalist',
 'Human Resources Senior Specialist',
 'Student at Humber College and Aspiring Human Resources Generalist',
 'Seeking Human Resources HRIS and Generalist Positions',
 'Student at Chapman University',
 'SVP Chief Human Resources Officer Marketing Communications CSR Officer ENGIE Houston The Woodlands Energy General Professional in Human Resources Senior Professional in Human Resources',
 'Human Resources Coordinator at InterContinental Buckhead Atlanta',
 '2019 C T Bauer College of Business Graduate Magna Cum Laude and aspiring Human Resources professional',
 '2019 C T Bauer College of Business Graduate Magna Cum Laude and aspiring Human Resources professional',
 'Native English Teacher at EPIK English Program in Korea',
 'Aspiring Human Resources Professional',
 'People Development Coordinator at Ryan',
 '2019 C T Bauer College of Business Graduate Magna Cum Laude and aspiring Human Resources professional',
 'Native English Teacher at EPIK English Program in Korea',
 'Aspiring Human Resources Professional',
 'People Development Coordinator at Ryan',
 'Advisory Board Member at Celal Bayar University',
 'Aspiring Human Resources Specialist',
 'Student at Humber College and Aspiring Human Resources Generalist',
 'Human Resources Senior Specialist',
 'Aspiring Human Resources Management student seeking an internship',
 'Seeking Human Resources Opportunities',
 'Aspiring Human Resources Management student seeking an internship',
 'Seeking Human Resources Opportunities',
 '2019 C T Bauer College of Business Graduate Magna Cum Laude and aspiring Human Resources professional',
 'Native English Teacher at EPIK English Program in Korea',
 'Aspiring Human Resources Professional',
 'People Development Coordinator at Ryan',
 'Advisory Board Member at Celal Bayar University',
 'Aspiring Human Resources Specialist',
 'Student at Humber College and Aspiring Human Resources Generalist',
 'Human Resources Senior Specialist',
 'Student at Humber College and Aspiring Human Resources Generalist',
 'Seeking Human Resources HRIS and Generalist Positions',
 'Student at Chapman University',
 'SVP Chief Human Resources Officer Marketing Communications CSR Officer ENGIE Houston The Woodlands Energy General Professional in Human Resources Senior Professional in Human Resources',
 'Human Resources Coordinator at InterContinental Buckhead Atlanta',
 '2019 C T Bauer College of Business Graduate Magna Cum Laude and aspiring Human Resources professional',
 'Native English Teacher at EPIK English Program in Korea',
 'Aspiring Human Resources Professional',
 'People Development Coordinator at Ryan',
 'Advisory Board Member at Celal Bayar University',
 'Aspiring Human Resources Specialist',
 'Student at Humber College and Aspiring Human Resources Generalist',
 'Human Resources Senior Specialist',
 'Student at Humber College and Aspiring Human Resources Generalist',
 'Seeking Human Resources HRIS and Generalist Positions',
 'Student at Chapman University',
 'SVP Chief Human Resources Officer Marketing Communications CSR Officer ENGIE Houston The Woodlands Energy General Professional in Human Resources Senior Professional in Human Resources',
 'Human Resources Coordinator at InterContinental Buckhead Atlanta',
 '2019 C T Bauer College of Business Graduate Magna Cum Laude and aspiring Human Resources professional',
 'Aspiring Human Resources Professional',
 'People Development Coordinator at Ryan',
 'Aspiring Human Resources Specialist',
 'Human Resources Senior Specialist',
 'Seeking Human Resources HRIS and Generalist Positions',
 'Student at Chapman University',
 'SVP Chief Human Resources Officer Marketing Communications CSR Officer ENGIE Houston The Woodlands Energy General Professional in Human Resources Senior Professional in Human Resources',
 'Human Resources Coordinator at InterContinental Buckhead Atlanta',
 'Experienced Retail Manager and aspiring Human Resources Professional',
 'Human Resources Staffing and Recruiting Professional',
 'Human Resources Specialist at Luxottica',
 'Director of Human Resources North America Groupe Beneteau',
 'Retired Army National Guard Recruiter office manager seeking a position in Human Resources',
 'Human Resources Generalist at ScottMadden Inc',
 'Business Management Major and Aspiring Human Resources Manager',
 'Aspiring Human Resources Manager seeking internship in Human Resources',
 'Human Resources Professional',
 'Nortia Staffing is seeking Human Resources Payroll Administrative Professionals 408 709 2621',
 'Aspiring Human Resources Professional Passionate about helping to create an inclusive and engaging work environment',
 'Human Resources Conflict Management Policies Procedures Talent Management Benefits Compensation',
 'Human Resources Generalist at Schwan s',
 'Liberal Arts Major Aspiring Human Resources Analyst',
 'Junior MES Engineer Information Systems',
 'Senior Human Resources Business Partner at Heil Environmental',
 'Aspiring Human Resources Professional An energetic and Team Focused Leader',
 'Human Resources Manager at Endemol Shine North America',
 'Human Resources professional for the world leader in GIS software',
 'RRP Brand Portfolio Executive at JTI Japan Tobacco International',
 'Information Systems Specialist and Programmer with a love for data and organization',
 'Bachelor of Science in Biology from Victoria University of Wellington',
 'Human Resources Management Major',
 'Director Human Resources at EY',
 'Undergraduate Research Assistant at Styczynski Lab',
 'Lead Official at Western Illinois University',
 'Seeking employment opportunities within Customer Service or Patient Care',
 'Admissions Representative at Community medical center long beach',
 'Seeking Human Resources Opportunities Open to travel and relocation',
 'Student at Westfield State University',
 'Student at Indiana University Kokomo Business Management Retail Manager at Delphi Hardware and Paint',
 'Aspiring Human Resources Professional',
 'Student',
 'Seeking Human Resources Position',
 'Aspiring Human Resources Manager Graduating May 2020 Seeking an Entry Level Human Resources Position in St Louis',
 'Human Resources Generalist at Loparex',
 'Business Intelligence and Analytics at Travelers',
 'Always set them up for Success',
 'Director Of Administration at Excellence Logging',
 'seeking human resources']

In [87]:
vectorizer = Vectorizer()
vectorizer.bert(bert_list)
vectors = vectorizer.vectors

Vectorization done on cpu device

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_layer_norm.weight', 'vocab_projector.weight', 'vocab_projector.bias', 'vocab_transform.weight', 'vocab_transform.bias', 'vocab_layer_norm.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [88]:
dist_1 = spatial.distance.cosine(vectors[-1], vectors[0])
dist_2 = spatial.distance.cosine(vectors[-1], vectors[2])
print('dist_1: {0}, dist-2: {1}'.format(dist_1, dist_2))

dist_1: 0.07078111171722412, dist-2: 0.01500558853149414

In [98]:
scores = []
for num in range(len(bert_list) - 1):
    scores.append(1 - spatial.distance.cosine(vectors[num], vectors[-1]))
    
test_df['bert_fit'] = scores
test_df

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,0.929219
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+,0.948172
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.984994
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,0.973138
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,0.935457
...,...,...,...,...,...
99,100,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103,0.914459
100,101,Human Resources Generalist at Loparex,"Raleigh-Durham, North Carolina Area",500+,0.982065
101,102,Business Intelligence and Analytics at Travelers,Greater New York City Area,49,0.976543
102,103,Always set them up for Success,Greater Los Angeles Area,500+,0.983066
103,104,Director Of Administration at Excellence Logging,"Katy, Texas",500+,0.968243

In [136]:
test_df.sort_values(by=['word2vec_fit'], ascending=False).head(15)

,id,job_title,location,connection,fit,word2vec_fit
98,99,Seeking Human Resources Position,"Las Vegas, Nevada Area",48,0.994894,0.920869
27,28,Seeking Human Resources Opportunities,"Chicago, Illinois",390,0.996201,0.903864
29,30,Seeking Human Resources Opportunities,"Chicago, Illinois",390,0.996201,0.903864
72,73,"Aspiring Human Resources Manager, seeking inte...","Houston, Texas Area",7,0.975402,0.839220
9,10,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.974998,0.808101
39,40,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.974998,0.808101
52,53,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.974998,0.808101
61,62,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.974998,0.808101
73,74,Human Resources Professional,Greater Boston Area,16,0.991686,0.793325
67,68,Human Resources Specialist at Luxottica,Greater New York City Area,500+,0.974341,0.767376
100,101,Human Resources Generalist at Loparex,"Raleigh-Durham, North Carolina Area",500+,0.982065,0.750962
77,78,Human Resources Generalist at Schwan's,Amerika Birleşik Devletleri,500+,0.982967,0.750962
87,88,Human Resources Management Major,"Milpitas, California",18,0.990193,0.747540
59,60,Aspiring Human Resources Specialist,Greater New York City Area,1,0.987985,0.743151
5,6,Aspiring Human Resources Specialist,Greater New York City Area,1,0.987985,0.743151

## TF-IDF

In [147]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(bert_list)

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [154]:
test_df['tfidf_fit'] = cosine_sim[-1][:-1]

In [162]:
test_df.sort_values(by=['word2vec_fit'], ascending=False).head(50)

,id,job_title,location,connection,fit,word2vec_fit,tfidf_fit
98,99,Seeking Human Resources Position,"Las Vegas, Nevada Area",48,0.994894,0.920869,0.625865
27,28,Seeking Human Resources Opportunities,"Chicago, Illinois",390,0.996201,0.903864,0.646155
29,30,Seeking Human Resources Opportunities,"Chicago, Illinois",390,0.996201,0.903864,0.646155
72,73,"Aspiring Human Resources Manager, seeking inte...","Houston, Texas Area",7,0.975402,0.839220,0.552318
9,10,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.974998,0.808101,0.447527
39,40,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.974998,0.808101,0.447527
52,53,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.974998,0.808101,0.447527
61,62,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500+,0.974998,0.808101,0.447527
73,74,Human Resources Professional,Greater Boston Area,16,0.991686,0.793325,0.351856
67,68,Human Resources Specialist at Luxottica,Greater New York City Area,500+,0.974341,0.767376,0.170633
100,101,Human Resources Generalist at Loparex,"Raleigh-Durham, North Carolina Area",500+,0.982065,0.750962,0.172445
77,78,Human Resources Generalist at Schwan's,Amerika Birleşik Devletleri,500+,0.982967,0.750962,0.172445
87,88,Human Resources Management Major,"Milpitas, California",18,0.990193,0.747540,0.183370
59,60,Aspiring Human Resources Specialist,Greater New York City Area,1,0.987985,0.743151,0.261115
5,6,Aspiring Human Resources Specialist,Greater New York City Area,1,0.987985,0.743151,0.261115
23,24,Aspiring Human Resources Specialist,Greater New York City Area,1,0.987985,0.743151,0.261115
35,36,Aspiring Human Resources Specialist,Greater New York City Area,1,0.987985,0.743151,0.261115
48,49,Aspiring Human Resources Specialist,Greater New York City Area,1,0.987985,0.743151,0.261115
74,75,"Nortia Staffing is seeking Human Resources, Pa...","San Jose, California",500+,0.941422,0.739170,0.226194
99,100,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103,0.914459,0.729863,0.283608
93,94,Seeking Human Resources Opportunities. Open t...,Amerika Birleşik Devletleri,415,0.969101,0.726077,0.302663
57,58,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.984994,0.700596,0.292820
45,46,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.984994,0.700596,0.292820
32,33,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.984994,0.700596,0.292820
96,97,Aspiring Human Resources Professional,"Kokomo, Indiana Area",71,0.984994,0.700596,0.292820
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.984994,0.700596,0.292820
20,21,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.984994,0.700596,0.292820
16,17,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,0.984994,0.700596,0.292820
7,8,HR Senior Specialist,San Francisco Bay Area,500+,0.984148,0.699413,0.224059
37,38,HR Senior Specialist,San Francisco Bay Area,500+,0.984148,0.699413,0.224059
50,51,HR Senior Specialist,San Francisco Bay Area,500+,0.984148,0.699413,0.224059
60,61,HR Senior Specialist,San Francisco Bay Area,500+,0.984148,0.699413,0.224059
25,26,HR Senior Specialist,San Francisco Bay Area,500+,0.984148,0.699413,0.224059
26,27,Aspiring Human Resources Management student se...,"Houston, Texas Area",500+,0.965308,0.696512,0.406702
28,29,Aspiring Human Resources Management student se...,"Houston, Texas Area",500+,0.965308,0.696512,0.406702
11,12,"SVP, CHRO, Marketing & Communications, CSR Off...","Houston, Texas Area",500+,0.840423,0.689503,0.176518
41,42,"SVP, CHRO, Marketing & Communications, CSR Off...","Houston, Texas Area",500+,0.840423,0.689503,0.176518
54,55,"SVP, CHRO, Marketing & Communications, CSR Off...","Houston, Texas Area",500+,0.840423,0.689503,0.176518
63,64,"SVP, CHRO, Marketing & Communications, CSR Off...","Houston, Texas Area",500+,0.840423,0.689503,0.176518
70,71,"Human Resources Generalist at ScottMadden, Inc.","Raleigh-Durham, North Carolina Area",500+,0.967992,0.674703,0.135955
66,67,"Human Resources, Staffing and Recruiting Profe...","Jackson, Mississippi Area",500+,0.962998,0.673157,0.140963
88,89,Director Human Resources at EY,Greater Atlanta Area,349,0.973498,0.668984,0.155136
71,72,Business Management Major and Aspiring Human R...,"Monroe, Louisiana Area",5,0.965552,0.652129,0.132629
80,81,Senior Human Resources Business Partner at Hei...,"Chattanooga, Tennessee Area",455,0.961893,0.639890,0.108755
76,77,Human Resources|\nConflict Management|\nPolici...,Dallas/Fort Worth Area,409,0.972505,0.621532,0.076297
83,84,Human Resources professional for the world lea...,"Highland, California",50,0.955671,0.612195,0.090687
42,43,Human Resources Coordinator at InterContinenta...,"Atlanta, Georgia",500+,0.965631,0.605437,0.134092
12,13,Human Resources Coordinator at InterContinenta...,"Atlanta, Georgia",500+,0.965631,0.605437,0.134092
55,56,Human Resources Coordinator at InterContinenta...,"Atlanta, Georgia",500+,0.965631,0.605437,0.134092
64,65,Human Resources Coordinator at InterContinenta...,"Atlanta, Georgia",500+,0.965631,0.605437,0.134092

## GloVe

In [165]:
glove_path = './glove.6B.300d.txt'
word2vec_output_file = 'glove.6B.300d.txt.word2vec'
glove2word2vec(glove_path, word2vec_output_file)

(400000, 300)

In [167]:
vectorizer = Vectorizer()
vectorizer.word2vec(job_desc_list, pretrained_vectors_path= './glove.6B.300d.txt')
vectors = vectorizer.vectors

ValueError: invalid literal for int() with base 10: 'the'

In [ ]:
dist_1 = spatial.distance.cosine(vectors[-1], vectors[0])
dist_2 = spatial.distance.cosine(vectors[-1], vectors[2])
print('dist_1: {0}, dist-2: {1}'.format(dist_1, dist_2))

In [ ]:
scores = []
for num in range(len(bert_list) - 1):
    scores.append(1 - spatial.distance.cosine(vectors[num], vectors[-1]))
    
test_df['bert_fit'] = scores
test_df